# @package _global_
# defaults:
#   - baseline/weischedules/ei

schedule_id: AWEI_${policy.atol_rel} (${policy.track_attitude}) (New Switch)

policy:
  _target_: awei.adaptive_weighted_ei.AWEIPolicy
  atol_rel: 0.1
  track_attitude: until_inc_change

# smac_kwargs:
#   runhistory_encoder:
#     _target_: smac.runhistory.encoder.RunHistoryLogScaledEncoder
