# @package _global_
defaults:
  - ../weischedule

schedule_id: EI (v) -> PI (v), switch after 75%

schedule_prototype:
  - [0.5, 0.75]  # first EI
  - [1, 0.25]  # then PI

smac_kwargs:
  acquisition_function:
    _target_: dacbo.weighted_expected_improvement.EIPI
