# @package _global_
defaults:
  - ../weischedule

schedule_id: EI (v) -> PI (v), switch after 50%

schedule_prototype:
  - [0.5, 0.5]  # first half EI
  - [1, 0.5]  # second half PI

smac_kwargs:
  acquisition_function:
    _target_: dacbo.weighted_expected_improvement.EIPI
